### ISSUE TITLE
GBIF terms of use, citation, etc.

### ISSUE THREAD

**Issue by dnoesgaard** [eveskew/plant_rapid_assessment#1]
Hi there,

I was directed to this repo from this [bioRxiv preprint](https://www.biorxiv.org/content/10.1101/2020.12.14.413906v1.full).

As you may be aware, all use of GBIF-mediated data is subject to the GBIF [terms of use](https://www.gbif.org/terms) and specifically the [data user agreement](https://www.gbif.org/terms/data-user). An important part of this agreement—and a key component in the open data structure of GBIF—is that users **must** publicly acknowledge the the data publishers whose data they use, when publishing results in e.g. journal articles.

Have you given this any thought? Happy to discuss options!

(I work for the GBIF Secretariat)

**Comment by eveskew** [comment]
Hi Daniel,

Thanks for bringing this issue up. It's something we've been thinking about.

For various reasons (size of a single raw data download, the fact we've got the workflow already set up), it's much preferable for us to pull records through `rgbif` rather than download through the GBIF website. But this slightly complicates the attribution step.

I _thought_ we'd be able to use the `gbif_citation()` function to pull citations for all of our occurrence records. But it seems in the time since our original data downloads that some occurrence keys have disappeared from GBIF. Is this expected behavior? It looks like when I do a fresh pull of a given species' occurrence records that the existing records we have are in there but maybe slightly tweaked (lat/longs slightly changed, etc.). So I'm guessing that the GBIF record has either been modified or deleted in the interim with an associated change in the GBIF occurrence key, which means citations for some of our existing occurrence records are no longer retrievable.

In any case, would it be acceptable for you all if we ran our entire workflow fresh from the beginning and included a supplemental file with the dataset citations for all of the records we end up using in our final analysis?

**Comment by dnoesgaard** [comment]
Hi Evan,

Thanks for your response.

Unfortunately, occurrences keys are not persistent and in some cases records are deleted. For citation purposes it is therefore more relevant and important to retain information about the parent dataset (column datasetKey), as this UUID is persistent.

For your own analysis I would think that matching up as many occurrences as possible to their parent datasets would be great, but my main focus would be other users who could re-use the workflow in the future. gbif_citation() is a great helper, but I would perhaps consider using our new [derived dataset](https://www.gbif.org/citation-guidelines#derivedDatasets) service, that takes a list of datasetKeys with counts and returns a unique DOI for citation. You could consider implementing the service fully—or simply helping the users prepare the data required to use the service and provide a link to it. While the service hasn't been fully documented yet, it's main functions are described here: https://github.com/gbif/registry/blob/c269dba66701cb634ba6ed1a7eefca754d3de2cf/docs/derived-dataset.md

Let me know what you think. I look forward to hearing from you again. I'm also happy to help match up records for your own analysis if it could help.

**Comment by eveskew** [comment]
Awesome! This is quite helpful for understanding what happened with the occurrence keys we previously pulled down.

Here's what I'm thinking: since some of our occurrence records may have changed/been deleted since we first drafted the paper and since some GBIF records have certainly been added since then, it probably makes sense for us to do a fresh data download at this stage of our revision process. This will also allow us the opportunity to pull down the dataset keys for all the records we harvest. In our original download, I tried to query the API using `rgbif` for only the columns that I thought would be critical for analysis (since we're dealing with millions of records, having fewer columns actually does make some noitceable difference in size on disk). I had grabbed the occurrence keys, but not the dataset keys, unfortunately. But that can be remedied with fresh data.

Before I restart the process, I just want to be double sure I'm thinking it through correctly. All I'll need are the dataset keys associated with the occurrence records and the counts for each of those dataset keys in the final dataset? If that's it, then I'll definitely use the derived dataset service, and that's a fantastic idea for GBIF users. I can re-run our entire workflow and then output a citations metadata file with the unique dataset keys and number of appearances in the final, cleaned dataset. That's the info I'll submit to get our unique DOI back for citation in the paper. Sound right?

**Comment by dnoesgaard** [comment]
Yup, that sounds just about perfect. In the interest of reproducibility, of course you'll want to keep the columns you need for your analysis as well, but for the purpose of getting a DOI, you just need the datasetKeys. 

Here's an example of the input required by the service—but there's also a [GUI](https://www.gbif.org/derived-dataset/register) if you prefer that:

```
{
  "title": "Data used in Turner KG, Fréville H and Rieseberg LH (2015) Adaptive plasticity and niche expansion in an invasive thistle. Ecology and Evolution. Wiley 5(15): 3183–3197. Available at: https://doi.org/10.1002/ece3.1599",
  "sourceUrl": "https://doi.org/10.5061/dryad.60p5d",
  "relatedDatasets": {
"07fd0d79-4883-435f-bba1-58fef110cd13": 252,
"086a644d-6cbe-43b7-b7c7-d33d36028d7f": 2,
"0fb2c370-a84f-11de-978d-b8a03c50a862": 25,
"2fd02649-fc08-4957-9ac5-2830e072c097": 4,
"36c6ba38-1387-11e2-bb2e-00145eb45e9a": 155,
"38b4c89f-584c-41bb-bd8f-cd1def33e92f": 8,
"4cf3eec1-b902-40c9-b15b-05c5fe5928b6": 5,
"4e22dd77-6ba1-4256-a692-64fecdf38ea7": 23,
"4f72060d-2c72-4d5f-addc-8d1b1049c78a": 3,
"4fa894f4-b6c6-4ec0-b816-9bb03b3ca106": 35,
"5288946d-5fcf-4b53-8fd3-74f4cc6b53fc": 4,
"5325ba61-44e7-4d92-ac11-868b3294b3bb": 3,
"5df38344-b821-49c2-8174-cf0f29f4df0d": 1,
"69f0f5c2-08b9-11e3-ab1f-00145eb45e9a": 2,
"6a122346-08b9-11e3-ab1f-00145eb45e9a": 3,
"6ac3f774-d9fb-4796-b3e9-92bf6c81c084": 17,
"7133ff0a-f762-11e1-a439-00145eb45e9a": 16,
"7a2660bc-f762-11e1-a439-00145eb45e9a": 2,
"7b904404-f762-11e1-a439-00145eb45e9a": 3,
"7bd65a7a-f762-11e1-a439-00145eb45e9a": 5,
"7f5260c2-f762-11e1-a439-00145eb45e9a": 1,
"82983b4e-f762-11e1-a439-00145eb45e9a": 3,
"82c11e9c-f762-11e1-a439-00145eb45e9a": 9,
"8310f570-f762-11e1-a439-00145eb45e9a": 48,
"834a4794-f762-11e1-a439-00145eb45e9a": 2,
"834b7330-f762-11e1-a439-00145eb45e9a": 1,
"84aa5ee4-f762-11e1-a439-00145eb45e9a": 25,
"85714c48-f762-11e1-a439-00145eb45e9a": 2,
"85ac3c18-f762-11e1-a439-00145eb45e9a": 12,
"86221faa-f762-11e1-a439-00145eb45e9a": 1,
"90ae13f0-288f-4108-b741-ac8a0f9e0878": 1,
"940821c0-3269-11df-855a-b8a03c50a862": 1,
"9587f32a-f762-11e1-a439-00145eb45e9a": 2,
"95aef98e-f762-11e1-a439-00145eb45e9a": 12,
"95c938a8-f762-11e1-a439-00145eb45e9a": 9,
"962f59bc-f762-11e1-a439-00145eb45e9a": 6,
"963f12d0-f762-11e1-a439-00145eb45e9a": 1,
"966426ce-f762-11e1-a439-00145eb45e9a": 1,
"aab0cf80-0c64-11dd-84d1-b8a03c50a862": 10,
"baa86fb2-7346-4507-a34f-44e4c1bd0d57": 3,
"c01696db-a5fe-4d3a-8b26-90760604774b": 1,
"d0aa984e-c6d3-45ee-8fc0-df1df8f4126b": 2,
"d4aa2255-f927-4220-af22-2958298733b7": 4,
"e45c7d91-81c6-4455-86e3-2965a5739b1f": 6,
"f934f8e2-32ca-46a7-b2f8-b032a4740454": 1
  }
}
```
And the output: https://doi.org/10.15468/dd.tpzpa4

Let me know how it goes!

**Comment by eveskew** [comment]
Hi Daniel,

Success! 

I was able to document our derived dataset (https://www.gbif.org/derivedDataset/10.15468/dd.df4evh) very easily. One minor hiccup: I initially uploaded a CSV with the metadata and hit a somewhat uninformative error message. I figured it was because I had column headers ("datasetKey" and "nOccurrencesInDerivedDataset"), and sure enough, once I removed those, everything was fine. Maybe folks will figure this out on their own, but could be good to clarify that the CSV can _only_ contain those types of values?

And one final question: you prefer for authors to use the suggested citation verbatim?

`Derived dataset GBIF.org (21 July 2021) Filtered export of GBIF occurrence data https://doi.org/10.15468/dd.df4evh`

I was thinking I would include the title I assigned, but if you all prefer it as indicated, that's what we'll go with.

Thanks!
Evan

**Comment by dnoesgaard** [comment]
Hi Evan,

Excellent! I'll make sure that the derived dataset is flagged and linked to the preprint!

Good point about the CSV header, I'll see what we can do about making this clearer.

About the citation, to be honest, you can change it as much as you like, as long as the DOI is included. 

Best,
Daniel

**Comment by eveskew** [comment]
Awesome! Will do!
